// <auto-generated />
using HomeServerPage.Data.Astronomy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeServerPage.Migrations.AstronomyDb
{
    [DbContext(typeof(AstronomyDbContext))]
    [Migration("20260905134209_AddObservationPoints")]
    partial class AddObservationPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.DeepSkyObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catalog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DeepSkyObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Catalog = "NGC224",
                            Height = 60.0,
                            Symbol = "M31",
                            Width = 190.0
                        },
                        new
                        {
                            Id = 2,
                            Catalog = "Mel25",
                            Height = 185.0,
                            Symbol = "C41",
                            Width = 185.0
                        },
                        new
                        {
                            Id = 3,
                            Catalog = "NGC1909",
                            Height = 60.0,
                            Symbol = "IC2118",
                            Width = 180.0
                        },
                        new
                        {
                            Id = 4,
                            Catalog = "NGC7000",
                            Height = 30.0,
                            Symbol = "C20",
                            Width = 120.0
                        },
                        new
                        {
                            Id = 5,
                            Catalog = "NGC6960",
                            Height = 15.0,
                            Symbol = "C34",
                            Width = 110.0
                        },
                        new
                        {
                            Id = 6,
                            Catalog = "NGC6992",
                            Height = 25.0,
                            Symbol = "C33",
                            Width = 100.0
                        },
                        new
                        {
                            Id = 7,
                            Catalog = "",
                            Height = 100.0,
                            Symbol = "M45",
                            Width = 100.0
                        },
                        new
                        {
                            Id = 8,
                            Catalog = "NGC1976",
                            Height = 60.0,
                            Symbol = "M42",
                            Width = 90.0
                        },
                        new
                        {
                            Id = 9,
                            Catalog = "IC4715",
                            Height = 90.0,
                            Symbol = "M24",
                            Width = 90.0
                        },
                        new
                        {
                            Id = 10,
                            Catalog = "IC1396",
                            Height = 89.0,
                            Symbol = "IC1396",
                            Width = 89.0
                        },
                        new
                        {
                            Id = 11,
                            Catalog = "NGC2237",
                            Height = 60.0,
                            Symbol = "C49",
                            Width = 80.0
                        },
                        new
                        {
                            Id = 12,
                            Catalog = "NGC598",
                            Height = 42.0,
                            Symbol = "M33",
                            Width = 79.0
                        },
                        new
                        {
                            Id = 13,
                            Catalog = "IC1805",
                            Height = 60.0,
                            Symbol = "IC1805",
                            Width = 60.0
                        },
                        new
                        {
                            Id = 14,
                            Catalog = "Sh2-155",
                            Height = 30.0,
                            Symbol = "C9",
                            Width = 50.0
                        },
                        new
                        {
                            Id = 15,
                            Catalog = "IC405",
                            Height = 30.0,
                            Symbol = "C31",
                            Width = 50.0
                        },
                        new
                        {
                            Id = 16,
                            Catalog = "NGC6523",
                            Height = 30.0,
                            Symbol = "M8",
                            Width = 45.0
                        },
                        new
                        {
                            Id = 17,
                            Catalog = "NGC6974",
                            Height = 30.0,
                            Symbol = "NGC6974",
                            Width = 45.0
                        },
                        new
                        {
                            Id = 18,
                            Catalog = "IC5070",
                            Height = 30.0,
                            Symbol = "IC5070",
                            Width = 40.0
                        },
                        new
                        {
                            Id = 19,
                            Catalog = "IC1848",
                            Height = 10.0,
                            Symbol = "IC1848",
                            Width = 40.0
                        },
                        new
                        {
                            Id = 20,
                            Catalog = "NGC281",
                            Height = 30.0,
                            Symbol = "NGC281",
                            Width = 35.0
                        },
                        new
                        {
                            Id = 21,
                            Catalog = "NGC281",
                            Height = 30.0,
                            Symbol = "NGC281",
                            Width = 35.0
                        },
                        new
                        {
                            Id = 22,
                            Catalog = "NGC869",
                            Height = 30.0,
                            Symbol = "C14",
                            Width = 30.0
                        },
                        new
                        {
                            Id = 23,
                            Catalog = "NGC884",
                            Height = 30.0,
                            Symbol = "C14",
                            Width = 30.0
                        },
                        new
                        {
                            Id = 24,
                            Catalog = "NGC2024",
                            Height = 30.0,
                            Symbol = "NGC2024",
                            Width = 30.0
                        },
                        new
                        {
                            Id = 25,
                            Catalog = "NGC5457",
                            Height = 28.399999999999999,
                            Symbol = "M101",
                            Width = 28.399999999999999
                        },
                        new
                        {
                            Id = 26,
                            Catalog = "NGC6514",
                            Height = 28.0,
                            Symbol = "M20",
                            Width = 28.0
                        },
                        new
                        {
                            Id = 27,
                            Catalog = "NGC253",
                            Height = 6.0,
                            Symbol = "C65",
                            Width = 26.399999999999999
                        },
                        new
                        {
                            Id = 28,
                            Catalog = "NGC3031",
                            Height = 12.0,
                            Symbol = "M81",
                            Width = 25.0
                        },
                        new
                        {
                            Id = 29,
                            Catalog = "NGC6205",
                            Height = 23.199999999999999,
                            Symbol = "M13",
                            Width = 23.199999999999999
                        },
                        new
                        {
                            Id = 30,
                            Catalog = "IC5146",
                            Height = 10.0,
                            Symbol = "C19",
                            Width = 20.0
                        },
                        new
                        {
                            Id = 31,
                            Catalog = "NGC6888",
                            Height = 10.0,
                            Symbol = "C27",
                            Width = 20.0
                        },
                        new
                        {
                            Id = 32,
                            Catalog = "NGC6405",
                            Height = 20.0,
                            Symbol = "M6",
                            Width = 20.0
                        },
                        new
                        {
                            Id = 33,
                            Catalog = "NGC1982",
                            Height = 20.0,
                            Symbol = "M43",
                            Width = 20.0
                        },
                        new
                        {
                            Id = 34,
                            Catalog = "NGC2264",
                            Height = 20.0,
                            Symbol = "NGC2264",
                            Width = 20.0
                        },
                        new
                        {
                            Id = 35,
                            Catalog = "IC2177",
                            Height = 20.0,
                            Symbol = "IC2177",
                            Width = 20.0
                        },
                        new
                        {
                            Id = 36,
                            Catalog = "NGC5904",
                            Height = 19.899999999999999,
                            Symbol = "M5",
                            Width = 19.899999999999999
                        },
                        new
                        {
                            Id = 37,
                            Catalog = "NGC205",
                            Height = 11.5,
                            Symbol = "M110",
                            Width = 19.5
                        },
                        new
                        {
                            Id = 38,
                            Catalog = "NGC6809",
                            Height = 19.100000000000001,
                            Symbol = "M55",
                            Width = 19.100000000000001
                        },
                        new
                        {
                            Id = 39,
                            Catalog = "NGC5272",
                            Height = 18.600000000000001,
                            Symbol = "M3",
                            Width = 18.600000000000001
                        },
                        new
                        {
                            Id = 40,
                            Catalog = "NGC4258",
                            Height = 7.0,
                            Symbol = "M106",
                            Width = 17.399999999999999
                        },
                        new
                        {
                            Id = 41,
                            Catalog = "NGC6656",
                            Height = 17.0,
                            Symbol = "M22",
                            Width = 17.0
                        },
                        new
                        {
                            Id = 42,
                            Catalog = "IC1613",
                            Height = 14.9,
                            Symbol = "C51",
                            Width = 16.600000000000001
                        },
                        new
                        {
                            Id = 43,
                            Catalog = "NGC7293",
                            Height = 12.0,
                            Symbol = "C63",
                            Width = 16.0
                        },
                        new
                        {
                            Id = 44,
                            Catalog = "NGC2323",
                            Height = 16.0,
                            Symbol = "M50",
                            Width = 16.0
                        },
                        new
                        {
                            Id = 45,
                            Catalog = "NGC663",
                            Height = 16.0,
                            Symbol = "C10",
                            Width = 16.0
                        },
                        new
                        {
                            Id = 46,
                            Catalog = "NGC4244",
                            Height = 1.8,
                            Symbol = "C26",
                            Width = 15.9
                        },
                        new
                        {
                            Id = 47,
                            Catalog = "NGC6822",
                            Height = 14.199999999999999,
                            Symbol = "C57",
                            Width = 15.4
                        },
                        new
                        {
                            Id = 48,
                            Catalog = "NGC4631",
                            Height = 2.7999999999999998,
                            Symbol = "C32",
                            Width = 15.199999999999999
                        },
                        new
                        {
                            Id = 49,
                            Catalog = "NGC7635",
                            Height = 8.0,
                            Symbol = "C11",
                            Width = 15.0
                        },
                        new
                        {
                            Id = 50,
                            Catalog = "NGC6694",
                            Height = 15.0,
                            Symbol = "M26",
                            Width = 15.0
                        },
                        new
                        {
                            Id = 51,
                            Catalog = "NGC6626",
                            Height = 15.0,
                            Symbol = "M28",
                            Width = 15.0
                        },
                        new
                        {
                            Id = 52,
                            Catalog = "NGC4565",
                            Height = 2.0,
                            Symbol = "C38",
                            Width = 14.9
                        },
                        new
                        {
                            Id = 53,
                            Catalog = "NGC5024",
                            Height = 14.4,
                            Symbol = "M53",
                            Width = 14.4
                        },
                        new
                        {
                            Id = 54,
                            Catalog = "NGC6266",
                            Height = 14.1,
                            Symbol = "M62",
                            Width = 14.1
                        },
                        new
                        {
                            Id = 55,
                            Catalog = "NGC6705",
                            Height = 14.0,
                            Symbol = "M11",
                            Width = 14.0
                        },
                        new
                        {
                            Id = 56,
                            Catalog = "NGC6705",
                            Height = 14.0,
                            Symbol = "C1",
                            Width = 14.0
                        },
                        new
                        {
                            Id = 57,
                            Catalog = "NGC147",
                            Height = 8.1999999999999993,
                            Symbol = "C17",
                            Width = 13.5
                        },
                        new
                        {
                            Id = 58,
                            Catalog = "NGC891",
                            Height = 2.7999999999999998,
                            Symbol = "C23",
                            Width = 13.1
                        },
                        new
                        {
                            Id = 59,
                            Catalog = "NGC5236",
                            Height = 12.0,
                            Symbol = "M83",
                            Width = 13.0
                        },
                        new
                        {
                            Id = 60,
                            Catalog = "NGC6531",
                            Height = 13.0,
                            Symbol = "M21",
                            Width = 13.0
                        },
                        new
                        {
                            Id = 61,
                            Catalog = "NGC7654",
                            Height = 13.0,
                            Symbol = "M52",
                            Width = 13.0
                        },
                        new
                        {
                            Id = 62,
                            Catalog = "NGC457",
                            Height = 13.0,
                            Symbol = "C13",
                            Width = 13.0
                        },
                        new
                        {
                            Id = 63,
                            Catalog = "NGC2360",
                            Height = 13.0,
                            Symbol = "C58",
                            Width = 13.0
                        },
                        new
                        {
                            Id = 64,
                            Catalog = "NGC5055",
                            Height = 7.0,
                            Symbol = "M63",
                            Width = 12.6
                        },
                        new
                        {
                            Id = 65,
                            Catalog = "NGC185",
                            Height = 10.4,
                            Symbol = "C18",
                            Width = 12.5
                        },
                        new
                        {
                            Id = 66,
                            Catalog = "NGC7078",
                            Height = 12.300000000000001,
                            Symbol = "M15",
                            Width = 12.300000000000001
                        },
                        new
                        {
                            Id = 67,
                            Catalog = "NGC6254",
                            Height = 12.199999999999999,
                            Symbol = "M10",
                            Width = 12.199999999999999
                        },
                        new
                        {
                            Id = 68,
                            Catalog = "NGC6218",
                            Height = 12.199999999999999,
                            Symbol = "M12",
                            Width = 12.199999999999999
                        },
                        new
                        {
                            Id = 69,
                            Catalog = "NGC6341",
                            Height = 12.199999999999999,
                            Symbol = "M92",
                            Width = 12.199999999999999
                        },
                        new
                        {
                            Id = 70,
                            Catalog = "NGC4736",
                            Height = 11.0,
                            Symbol = "M94",
                            Width = 12.0
                        },
                        new
                        {
                            Id = 71,
                            Catalog = "NGC1960",
                            Height = 12.0,
                            Symbol = "M36",
                            Width = 12.0
                        },
                        new
                        {
                            Id = 72,
                            Catalog = "NGC5907",
                            Height = 1.3,
                            Symbol = "NGC5907",
                            Width = 11.800000000000001
                        },
                        new
                        {
                            Id = 73,
                            Catalog = "NGC7089",
                            Height = 11.699999999999999,
                            Symbol = "M2",
                            Width = 11.699999999999999
                        },
                        new
                        {
                            Id = 74,
                            Catalog = "NGC6946",
                            Height = 9.8000000000000007,
                            Symbol = "C12",
                            Width = 11.199999999999999
                        },
                        new
                        {
                            Id = 75,
                            Catalog = "NGC5194",
                            Height = 6.5999999999999996,
                            Symbol = "M51",
                            Width = 11.0
                        },
                        new
                        {
                            Id = 76,
                            Catalog = "NGC4559",
                            Height = 4.9000000000000004,
                            Symbol = "C36",
                            Width = 11.0
                        },
                        new
                        {
                            Id = 77,
                            Catalog = "NGC6618",
                            Height = 11.0,
                            Symbol = "M17",
                            Width = 11.0
                        },
                        new
                        {
                            Id = 78,
                            Catalog = "NGC3034",
                            Height = 5.0,
                            Symbol = "M82",
                            Width = 10.5
                        },
                        new
                        {
                            Id = 79,
                            Catalog = "NGC4826",
                            Height = 5.0,
                            Symbol = "M64",
                            Width = 10.300000000000001
                        },
                        new
                        {
                            Id = 80,
                            Catalog = "NGC7331",
                            Height = 4.2000000000000002,
                            Symbol = "C30",
                            Width = 10.199999999999999
                        },
                        new
                        {
                            Id = 81,
                            Catalog = "NGC628",
                            Height = 9.4000000000000004,
                            Symbol = "M74",
                            Width = 10.0
                        },
                        new
                        {
                            Id = 82,
                            Catalog = "NGC2359",
                            Height = 5.0,
                            Symbol = "NGC2359",
                            Width = 10.0
                        },
                        new
                        {
                            Id = 83,
                            Catalog = "NGC4569",
                            Height = 4.4000000000000004,
                            Symbol = "M90",
                            Width = 9.9000000000000004
                        },
                        new
                        {
                            Id = 84,
                            Catalog = "NGC4472",
                            Height = 8.1999999999999993,
                            Symbol = "M49",
                            Width = 9.8000000000000007
                        },
                        new
                        {
                            Id = 85,
                            Catalog = "NGC4406",
                            Height = 6.2999999999999998,
                            Symbol = "M86",
                            Width = 9.8000000000000007
                        },
                        new
                        {
                            Id = 86,
                            Catalog = "NGC4590",
                            Height = 9.8000000000000007,
                            Symbol = "M68",
                            Width = 9.8000000000000007
                        },
                        new
                        {
                            Id = 87,
                            Catalog = "NGC1097",
                            Height = 6.5999999999999996,
                            Symbol = "C67",
                            Width = 9.4000000000000004
                        },
                        new
                        {
                            Id = 88,
                            Catalog = "NGC3627",
                            Height = 4.0999999999999996,
                            Symbol = "M66",
                            Width = 9.4000000000000004
                        },
                        new
                        {
                            Id = 89,
                            Catalog = "NGC4192",
                            Height = 2.2999999999999998,
                            Symbol = "M98",
                            Width = 9.4000000000000004
                        },
                        new
                        {
                            Id = 90,
                            Catalog = "NGC6715",
                            Height = 9.0999999999999996,
                            Symbol = "M54",
                            Width = 9.0999999999999996
                        },
                        new
                        {
                            Id = 91,
                            Catalog = "NGC3623",
                            Height = 2.2999999999999998,
                            Symbol = "M65",
                            Width = 9.0
                        },
                        new
                        {
                            Id = 92,
                            Catalog = "NGC6613",
                            Height = 9.0,
                            Symbol = "M18",
                            Width = 9.0
                        },
                        new
                        {
                            Id = 93,
                            Catalog = "NGC7099",
                            Height = 8.9000000000000004,
                            Symbol = "M30",
                            Width = 8.9000000000000004
                        },
                        new
                        {
                            Id = 94,
                            Catalog = "NGC4486",
                            Height = 6.5999999999999996,
                            Symbol = "M87",
                            Width = 8.6999999999999993
                        },
                        new
                        {
                            Id = 95,
                            Catalog = "NGC4594",
                            Height = 4.2000000000000002,
                            Symbol = "M104",
                            Width = 8.5999999999999996
                        },
                        new
                        {
                            Id = 96,
                            Catalog = "NGC3556",
                            Height = 2.3999999999999999,
                            Symbol = "M108",
                            Width = 8.5999999999999996
                        },
                        new
                        {
                            Id = 97,
                            Catalog = "NGC221",
                            Height = 6.5,
                            Symbol = "M32",
                            Width = 8.5
                        },
                        new
                        {
                            Id = 98,
                            Catalog = "IC434",
                            Height = 6.0,
                            Symbol = "IC434",
                            Width = 8.0
                        },
                        new
                        {
                            Id = 99,
                            Catalog = "NGC1952",
                            Height = 4.0,
                            Symbol = "M1",
                            Width = 8.0
                        },
                        new
                        {
                            Id = 100,
                            Catalog = "NGC2068",
                            Height = 8.0,
                            Symbol = "M78",
                            Width = 8.0
                        },
                        new
                        {
                            Id = 101,
                            Catalog = "NGC2362",
                            Height = 8.0,
                            Symbol = "C64",
                            Width = 8.0
                        },
                        new
                        {
                            Id = 102,
                            Catalog = "NGC3368",
                            Height = 5.2000000000000002,
                            Symbol = "M96",
                            Width = 7.7999999999999998
                        },
                        new
                        {
                            Id = 103,
                            Catalog = "NGC6681",
                            Height = 7.7999999999999998,
                            Symbol = "M70",
                            Width = 7.7999999999999998
                        },
                        new
                        {
                            Id = 104,
                            Catalog = "NGC1904",
                            Height = 7.7999999999999998,
                            Symbol = "M79",
                            Width = 7.7999999999999998
                        },
                        new
                        {
                            Id = 105,
                            Catalog = "NGC2506",
                            Height = 7.0,
                            Symbol = "C54",
                            Width = 7.5999999999999996
                        },
                        new
                        {
                            Id = 106,
                            Catalog = "NGC4649",
                            Height = 6.2000000000000002,
                            Symbol = "M60",
                            Width = 7.5999999999999996
                        },
                        new
                        {
                            Id = 107,
                            Catalog = "NGC4321",
                            Height = 6.0999999999999996,
                            Symbol = "M100",
                            Width = 7.5
                        },
                        new
                        {
                            Id = 108,
                            Catalog = "NGC3992",
                            Height = 4.4000000000000004,
                            Symbol = "M109",
                            Width = 7.5
                        },
                        new
                        {
                            Id = 109,
                            Catalog = "NGC4382",
                            Height = 5.9000000000000004,
                            Symbol = "M85",
                            Width = 7.4000000000000004
                        },
                        new
                        {
                            Id = 110,
                            Catalog = "NGC1068",
                            Height = 6.2999999999999998,
                            Symbol = "M77",
                            Width = 7.2999999999999998
                        },
                        new
                        {
                            Id = 111,
                            Catalog = "NGC3351",
                            Height = 4.4000000000000004,
                            Symbol = "M95",
                            Width = 7.2999999999999998
                        },
                        new
                        {
                            Id = 112,
                            Catalog = "NGC3115",
                            Height = 3.3999999999999999,
                            Symbol = "C53",
                            Width = 7.2999999999999998
                        },
                        new
                        {
                            Id = 113,
                            Catalog = "NGC6637",
                            Height = 7.0999999999999996,
                            Symbol = "M69",
                            Width = 7.0999999999999996
                        },
                        new
                        {
                            Id = 114,
                            Catalog = "NGC6611",
                            Height = 7.0,
                            Symbol = "M16",
                            Width = 7.0
                        },
                        new
                        {
                            Id = 115,
                            Catalog = "NGC6913",
                            Height = 7.0,
                            Symbol = "M29",
                            Width = 7.0
                        },
                        new
                        {
                            Id = 116,
                            Catalog = "NGC6882",
                            Height = 7.0,
                            Symbol = "C37",
                            Width = 7.0
                        },
                        new
                        {
                            Id = 117,
                            Catalog = "NGC4501",
                            Height = 3.7000000000000002,
                            Symbol = "M88",
                            Width = 6.7999999999999998
                        },
                        new
                        {
                            Id = 118,
                            Catalog = "NGC4374",
                            Height = 6.0,
                            Symbol = "M84",
                            Width = 6.7000000000000002
                        },
                        new
                        {
                            Id = 119,
                            Catalog = "NGC6402",
                            Height = 6.7000000000000002,
                            Symbol = "M14",
                            Width = 6.7000000000000002
                        },
                        new
                        {
                            Id = 120,
                            Catalog = "NGC4303",
                            Height = 5.9000000000000004,
                            Symbol = "M61",
                            Width = 6.5
                        },
                        new
                        {
                            Id = 121,
                            Catalog = "NGC5866",
                            Height = 3.1000000000000001,
                            Symbol = "M102",
                            Width = 6.5
                        },
                        new
                        {
                            Id = 122,
                            Catalog = "NGC4449",
                            Height = 4.9000000000000004,
                            Symbol = "C21",
                            Width = 6.2000000000000002
                        },
                        new
                        {
                            Id = 123,
                            Catalog = "NGC4697",
                            Height = 4.5,
                            Symbol = "C52",
                            Width = 6.2000000000000002
                        },
                        new
                        {
                            Id = 124,
                            Catalog = "NGC2419",
                            Height = 6.2000000000000002,
                            Symbol = "C25",
                            Width = 6.2000000000000002
                        },
                        new
                        {
                            Id = 125,
                            Catalog = "NGC6934",
                            Height = 6.2000000000000002,
                            Symbol = "C47",
                            Width = 6.2000000000000002
                        },
                        new
                        {
                            Id = 126,
                            Catalog = "NGC6838",
                            Height = 6.0999999999999996,
                            Symbol = "M71",
                            Width = 6.0999999999999996
                        });
                });

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.SensorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PixelSizeUm")
                        .HasColumnType("REAL");

                    b.Property<int>("ResolutionHeightPx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionWidthPx")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SensorHeightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("SensorWidthMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canon EOS 1100D",
                            PixelSizeUm = 5.1900000000000004,
                            ResolutionHeightPx = 2848,
                            ResolutionWidthPx = 4272,
                            SensorHeightMm = 14.800000000000001,
                            SensorWidthMm = 22.199999999999999
                        },
                        new
                        {
                            Id = 2,
                            Name = "ZWO ASI678MC",
                            PixelSizeUm = 2.0,
                            ResolutionHeightPx = 2160,
                            ResolutionWidthPx = 3840,
                            SensorHeightMm = 4.3200000000000003,
                            SensorWidthMm = 7.6799999999999997
                        });
                });

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.TelescopeEyepiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarellSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FieldOfView")
                        .HasColumnType("REAL");

                    b.Property<double>("FocalLength")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eyepieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarellSize = 1,
                            FieldOfView = 56.0,
                            FocalLength = 28.0,
                            Name = "Sky-Watcher 28mm LET 2\""
                        },
                        new
                        {
                            Id = 2,
                            BarellSize = 0,
                            FieldOfView = 52.0,
                            FocalLength = 10.0,
                            Name = "SUPER 10mm"
                        },
                        new
                        {
                            Id = 3,
                            BarellSize = 0,
                            FieldOfView = 52.0,
                            FocalLength = 25.0,
                            Name = "SUPER 25mm"
                        });
                });

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.TelescopeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Aperture")
                        .HasColumnType("REAL");

                    b.Property<double>("ApertureSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("FocalLength")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Telescopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aperture = 127.0,
                            ApertureSpeed = 11.800000000000001,
                            FocalLength = 1500.0,
                            Name = "Sky-Watcher BKMAK 127 OTAW",
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            Aperture = 72.0,
                            ApertureSpeed = 5.7999999999999998,
                            FocalLength = 420.0,
                            Name = "Sky-Watcher Evostar 72ED 72/420 F6",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Aperture = 130.0,
                            ApertureSpeed = 6.9000000000000004,
                            FocalLength = 900.0,
                            Name = "Sky-Watcher BK 1309 130/900",
                            Type = 1
                        });
                });

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.TelescopeLens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarellSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarellSize = 0,
                            Multiplier = 2.0,
                            Name = "Sky-Watcher 2x Barlow Lens"
                        },
                        new
                        {
                            Id = 2,
                            BarellSize = 1,
                            Multiplier = 0.5,
                            Name = "DO-GSO 0.5x 2\""
                        });
                });

            modelBuilder.Entity("HomeServerPage.Data.Astronomy.ObservationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ElevationMeters")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonEast")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonNorth")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonNorthEast")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonNorthWest")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonSouth")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonSouthEast")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonSouthWest")
                        .HasColumnType("REAL");

                    b.Property<double>("HorizonWest")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ObservationPoints", t =>
                        {
                            t.HasCheckConstraint("CK_ObservationPoints_HorizonAltitudes", "HorizonNorth >= 0 AND HorizonNorth <= 90 AND HorizonNorthEast >= 0 AND HorizonNorthEast <= 90 AND HorizonEast >= 0 AND HorizonEast <= 90 AND HorizonSouthEast >= 0 AND HorizonSouthEast <= 90 AND HorizonSouth >= 0 AND HorizonSouth <= 90 AND HorizonSouthWest >= 0 AND HorizonSouthWest <= 90 AND HorizonWest >= 0 AND HorizonWest <= 90 AND HorizonNorthWest >= 0 AND HorizonNorthWest <= 90");

                            t.HasCheckConstraint("CK_ObservationPoints_Latitude", "Latitude >= -90 AND Latitude <= 90");

                            t.HasCheckConstraint("CK_ObservationPoints_Longitude", "Longitude >= -180 AND Longitude <= 180");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
