// <auto-generated />
using HomeServerPage.Data.Astronomy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeServerPage.Migrations.AstronomyDb
{
    [DbContext(typeof(AstronomyDbContext))]
    partial class AstronomyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.SensorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PixelSizeUm")
                        .HasColumnType("REAL");

                    b.Property<int>("ResolutionHeightPx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionWidthPx")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SensorHeightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("SensorWidthMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Canon EOS 1100D",
                            PixelSizeUm = 5.1900000000000004,
                            ResolutionHeightPx = 2848,
                            ResolutionWidthPx = 4272,
                            SensorHeightMm = 14.800000000000001,
                            SensorWidthMm = 22.199999999999999
                        },
                        new
                        {
                            Id = 2,
                            Name = "ZWO ASI678MC",
                            PixelSizeUm = 2.0,
                            ResolutionHeightPx = 2160,
                            ResolutionWidthPx = 3840,
                            SensorHeightMm = 4.3200000000000003,
                            SensorWidthMm = 7.6799999999999997
                        });
                });

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.TelescopeEyepiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarellSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FieldOfView")
                        .HasColumnType("REAL");

                    b.Property<double>("FocalLength")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eyepieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarellSize = 1,
                            FieldOfView = 56.0,
                            FocalLength = 28.0,
                            Name = "Sky-Watcher 28mm LET 2\""
                        },
                        new
                        {
                            Id = 2,
                            BarellSize = 0,
                            FieldOfView = 52.0,
                            FocalLength = 10.0,
                            Name = "SUPER 10mm"
                        },
                        new
                        {
                            Id = 3,
                            BarellSize = 0,
                            FieldOfView = 52.0,
                            FocalLength = 25.0,
                            Name = "SUPER 25mm"
                        });
                });

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.TelescopeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Aperture")
                        .HasColumnType("REAL");

                    b.Property<double>("ApertureSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("FocalLength")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Telescopes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aperture = 127.0,
                            ApertureSpeed = 11.800000000000001,
                            FocalLength = 1500.0,
                            Name = "Sky-Watcher BKMAK 127 OTAW",
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            Aperture = 72.0,
                            ApertureSpeed = 5.7999999999999998,
                            FocalLength = 420.0,
                            Name = "Sky-Watcher Evostar 72ED 72/420 F6",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Aperture = 130.0,
                            ApertureSpeed = 6.9000000000000004,
                            FocalLength = 900.0,
                            Name = "Sky-Watcher BK 1309 130/900",
                            Type = 1
                        });
                });

            modelBuilder.Entity("HomeServerPage.Client.Data.Astronomy.Telescopes.TelescopeLens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BarellSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarellSize = 0,
                            Multiplier = 2.0,
                            Name = "Sky-Watcher 2x Barlow Lens"
                        },
                        new
                        {
                            Id = 2,
                            BarellSize = 1,
                            Multiplier = 0.5,
                            Name = "DO-GSO 0.5x 2\""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
