version: '3.8'

services:
  home-server-page:
    build:
      context: .
      dockerfile: HomeServerPage/HomeServerPage/Dockerfile
    container_name: blazor-home-server-page
    ports:
      - "8090:8080"
    restart: always
    volumes:
      - ./Database:/app/Database
      - ${PRIVATE_DATA_PATH}:/app/data/private
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AppSettings__PrivateDataPath=/app/data/private
