// <auto-generated />
using System;
using HomeServerPage.Data.Fridge;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeServerPage.Migrations
{
    [DbContext(typeof(FridgeDbContext))]
    [Migration("20260728185706_ChangeFridgeDtosPropertiesTypes")]
    partial class ChangeFridgeDtosPropertiesTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HomeServerPage.Data.Fridge.FridgeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("QuantityValue")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan?>("TimeAfterOpen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FridgeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
